version: "3"
services:
    svn:
     image: elleflorio/svn-server
     container_name: svn-server
     restart: always
     ports:
       - '18080:80'
       - '3690:3690'
     volumes:
       - /Users/yifei/docker-composer-list/svn-server/repos:/home/svn
       - /Users/yifei/docker-composer-list/svn-server/subversion:/etc/subversion
       # - /Users/yifei/docker-composer-list/svn-server/apache2:/run/apache2
