version: '3.1'

services:
  db:
    image: mysql:5.7
    #    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
