version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3.8.8-management-alpine
    ports:
    - "15692:15692"
    - "15672:15672"
    - "5672:5672"
    environment:
        RABBITMQ_DEFAULT_USER: root
        RABBITMQ_DEFAULT_PASS: root
    volumes:
        - ./data:/var/lib/rabbitmq
