#web:
#  image: 'gitlab/gitlab-ce:latest'
#  restart: always
#  hostname: 'gitlab.us'
#  environment:
#    GITLAB_OMNIBUS_CONFIG: |
#      external_url 'http://gitlab.us:9090'
#      gitlab_rails['gitlab_shell_ssh_port'] = 2224
#  ports:
#  - '9090:9090'
#  - '2224:22'

version: "3"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
#    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
    - '80:80'
    - '443:443'
    - '22:22'
    volumes:
    - '/Users/yifei/var/gitlab_home/config:/etc/gitlab'
    - '/Users/yifei/var/gitlab_home/logs:/var/log/gitlab'
    - '/Users/yifei/var/gitlab_home/data:/var/opt/gitlab'
