version: "3"
services:
  v2ray:
    image: jrohy/v2ray
    container_name: v2ray
    privileged: true
    restart: always
    ports:
      - 443:443
    volumes:
      - ./data/config.json:/etc/v2ray/config.json