# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:3.6.3
    restart: always
    container_name: mongodb-3.6.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/etc/mongo/mongod.conf.orig:/etc/mongod.conf.orig
      - ./data/db:/data/db
    ports:
        - 27017:27017
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: root
