version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "80:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: yifei
      PASSWORD: aaaa1111
    volumes:
      - ./data:/var/lib/dav